### ISSUE TITLE
As user, I would like to be able to configure a custom framework within the same file used to input the data

### ISSUE THREAD

**Issue by martinepunhcr** [UNHCR-Guatemala/A2SIT#6]
In the [ f_input.R](https://github.com/UNHCR-Guatemala/A2SIT/blob/main/R/f_input.R) module, the index framework is currently fixed through an RDS file (./inst/iMeta_aggs.RDS). Since the end user will need to customize the index structure, we need the framework configured by pulling the data from iMeta_aggs tab in the data_input file instead of the RDS file. Please, rewrite the code to enable that functionality.

## Client - Validation 

+ [ ] The end user is able to customize its own framework in the data_input and the module is able to build it

## Dev - Tech

+ [ ] Remove the RDS file and rewrite the code to build the index from the data_input file
+ [ ] Technical validation (check this does not have an impact on the subsequent modules)

**Comment by bluefoxr** [comment]
Ok noted, will get to this soon.

**Comment by bluefoxr** [comment]
Hi please see https://github.com/UNHCR-Guatemala/A2SIT/commit/d38d2e3d856e529de1ab40ad6477edf70fe3399f where I have enabled to read the metadata tab from the input file, and also uploaded the new example data spreadsheet to the repo.

I have added this to the Results branch which is waiting to be merged here: #12  rather than creating a separate branch.
