### ISSUE TITLE
As user, I would like to see standard UNHCR color and font in order to recognise the brand

### ISSUE THREAD

**Issue by Edouard-Legoupil** [UNHCR-Guatemala/A2SIT#8]
## Client - Validation 

+ [ ] Check that we have the right color

## Dev - Tech

+ [ ] Add a theming function

**Comment by Edouard-Legoupil** [comment]
Also the function used now https://github.com/UNHCR-Guatemala/A2SIT/blob/8-as-user-i-would-like-to-see-standard-unhcr-color-and-font-in-order-to-recognise-the-brand/R/theme.R comes from https://github.com/nik01010/dashboardthemes/blob/master/R/CreateTheme_shinyDashboardThemeDIY.R and is just a way to create a css

The package itself https://github.com/nik01010/dashboardthemes might be removed from CRAN -

We need to work with our designer [@vidonne](https://github.com/vidonne/) to get some UNHCR branded css for shinyDashboard - Will follow up with him on this!

**Comment by martinepunhcr** [comment]
In case it is valid, here you can find Cedric's quick guidance on UNHCR branding, with colors and fonts here: https://dataviz.unhcr.org/general_guidance/
Also, there is a package that may be handy for setting up the UI: https://rstudio.github.io/shinyuieditor/
But since this is the last step, we don't need to hurry. Let's wait for Cedric to make some time to give us a hand!

**Comment by Edouard-Legoupil** [comment]
https://spyrales.github.io/shinygouv/ --> inspirational for a UNHCR Shiny Template @vidonne
